name: Semgrep Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Run Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (for Semgrep)
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep with default rules
        run: semgrep scan --config=p/default --config=p/secrets --config=p/owasp-top-ten --error .
